### ISSUE TITLE
What is the latest version of TensorFlow supported by texar?

### ISSUE THREAD

**Issue by illcat** [asyml/texar#100]

**Comment by ZhitingHu** [comment]
Texar now supports up to TF-1.13

**Comment by illcat** [comment]
> Texar now supports up to TF-1.13

![image](https://user-images.githubusercontent.com/40688514/54105108-08897300-440d-11e9-9dc4-c12079e50c2b.png)
Why out-of-vocabulary tokens are NOT replaced with UNK, instead of replaced.

**Comment by ZhitingHu** [comment]
Use 
```python
vocab.id_to_token_map(data_batch["text_ids"])
```
to get text with OOV tokens replaced with UNK

**Comment by illcat** [comment]
Thank you。
