### ISSUE TITLE
GPT-2, why do we need encoder and decoder to train, but only decoder to predict

### ISSUE THREAD

**Issue by guotong1988** [asyml/texar#103]
![image](https://user-images.githubusercontent.com/4702353/54824433-de299680-4ce5-11e9-983e-7eda7de51e0e.png)
From the readme and this issue:https://github.com/asyml/texar/issues/92
I come up this question.

Thank you very much.

**Comment by ZhitingHu** [comment]
This use case is for *conditional* generation. For unconditional generation (i.e., language model), no encoder is needed and you can set `memory=None, memory_sequence_length=None` for during training

**Comment by guotong1988** [comment]
Thank you!
