### ISSUE TITLE
How to prepare the data for text generation task. Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [asyml/texar#104]
First, I'm not sure whether the model contains the encoder during training.

EOS means end-of-sentence. Encoder and decoder are part of transformer network.

If without-encoder, training time: 
```
target: [E, F, G, H, EOS]
decoder input: [0, E, F, G, H]
```

If without-encoder, testing time: 
```
decoder input: [0]
```

If with encoder, training time:
```
encoder input: [A, B, C, D]
target: [E, F, G, H, EOS]
decoder input: [0, E, F, G, H]
```

If with-encoder, testing time: 
```
encoder input: [A, B, C, D]
decoder input: [0]
```

Am I exact right?

I know it is beyond the topic of this project, but hope you could help.
Thank you and thank you.

**Comment by ZhitingHu** [comment]
Hey, what model did you refer to?

**Comment by guotong1988** [comment]
Transformer based model is OK～

**Comment by ZhitingHu** [comment]
The specifications of "decoder input" and "target" are correct in general. 

For "encoder input", sometimes we also add EOS to the end. See, e.g., the [default hparams of our PairedTextData](https://texar.readthedocs.io/en/latest/code/data.html#texar.data.PairedTextData.default_hparams).

**Comment by guotong1988** [comment]
Thank you.
