### ISSUE TITLE
Is there any way to avoid generation of trigrams during decoding?

### ISSUE THREAD

**Issue by Vibha111094** [asyml/texar#109]

**Comment by amudha1** [comment]
I am facing the problem with transformer decoder to be more specific.

**Comment by ZhitingHu** [comment]
Hi, not sure what you meant by *"generation of trigrams"*?

**Comment by amudha1** [comment]
I am basically trying a summarization task using BERT.
I am trying to understand if there is any parameter in the transformer_decoder function (somthing like openNMT )  to block ngrams. 

https://github.com/OpenNMT/OpenNMT-py/pull/642/commits/2e90375960c8f10072bbf078e571735f846a2e57

Something on these lines

**Comment by ZhitingHu** [comment]
Texar has not implemented this functionality. Any contributions are welcome

**Comment by amudha1** [comment]
Could I please get some pointers  .I will try my best to contribute.

**Comment by ZhitingHu** [comment]
Thanks. The transformer decoder does beam search [here](https://github.com/asyml/texar/blob/master/texar/modules/decoders/transformer_decoders.py#L808). Here is the definition of the [beam_search function](https://github.com/asyml/texar/blob/master/texar/utils/beam_search.py#L186)
