### ISSUE TITLE
How can we fine tune the GPT-2 model on our corpus.

### ISSUE THREAD

**Issue by saurabh-tripathi** [asyml/texar#117]
I wanted to fine-tune the GPT-2 model on a custom corpus so that it generates text similar to that. Is that possible using the library?  If yes then can you guide/point towards a relevant source?

**Comment by ZhitingHu** [comment]
Yes, it's convenient to fine-tune GPT-2. Please refer to **Ex. Use 3)** [here](https://github.com/asyml/texar/tree/master/examples/gpt-2#other-use-cases). Set both `memory` and `memory_sequence_length` to `None` if you're using GPT-2 as an unconditional language model.

**Comment by saurabh-tripathi** [comment]
Thank you
