### ISSUE TITLE
Making Input Different From Text

### ISSUE THREAD

**Issue by nvidiaman** [asyml/texar#118]
Hello,

I want to train an image captioning model with the transformer. How should I configure the input (i.e. VGG imagenet features) so that I can have an encoder-decoder model that is an image captioning model?

Please share any links or examples to implement this.

**Comment by ZhitingHu** [comment]
You may want to use the [`TFRecordData`](https://texar.readthedocs.io/en/latest/code/data.html#tfrecorddata) module to read and process image (feature) data. Please let us know if you have more questions on this

**Comment by nvidiaman** [comment]
@ZhitingHu thank you for the answer! I am keeping this issue open, as I am trying the TFRecordData and will update in a few days.

**Comment by nvidiaman** [comment]
@ZhitingHu i have a numpy array with the image features. What lines should I change in the current transformer model to adapt it to the image captioning code? 

Also, could you provide any starter code for tfrecord and where to place it in the current transformer machine translation code?

thank you.

**Comment by ZhitingHu** [comment]
Replace the [data part](https://github.com/asyml/texar/blob/master/examples/transformer/transformer_main.py#L57-L61) with TFRecordData module

You may refer to the [test code](https://github.com/asyml/texar/blob/master/texar/data/data/tfrecord_data_test.py#L153) for example of using `TFRecordData`

**Comment by nvidiaman** [comment]
@ZhitingHu Hi,

I tried replacing the input data part above to a tfrecord module containing, image-text pair,

and replace the load_data_numpy to load_data_

def load_data_():

   train = tf.data.TFRecordDataset("train.tfrecord")
   def _parse_function(example_proto):
      keys_to_features = {'x': tf.FixedLenFeature([], tf.float32),
                          'y': tf.FixedLenSequenceFeature([], tf.string, allow_missing=True)}
      parsed_features = tf.parse_single_example(example_proto, keys_to_features)
      return parsed_features['x'], parsed_features['y']

   train = train.map(_parse_function)

   return train, train, train

But I get error:

TypeError: 'MapDataset' object is not iterable

**Comment by nvidiaman** [comment]
@ZhitingHu the issue in more explaination: https://github.com/tensorflow/tensorflow/issues/28008

**Comment by ZhitingHu** [comment]
The [bert](https://github.com/asyml/texar/blob/master/examples/bert/bert_classifier_main.py#L100) and [gpt-2](https://github.com/asyml/texar/blob/master/examples/gpt-2/gpt2_train_main.py#L117) examples show how Texar's `TFRecordData` module can be used in this case.
