### ISSUE TITLE
Help on seq2seq_attn text generation

### ISSUE THREAD

**Issue by miikargh** [asyml/texar#123]
Hi!

First of all, thanks for the great work you've done here!

I trained a summarization model using the [seq2seq_attn](https://github.com/asyml/texar/blob/master/examples/seq2seq_attn/seq2seq_attn.py) example. I just added the following lines of code to save the model:
```python
saver = tf.train.Saver(max_to_keep=5)
save_path = saver.save(sess, os.path.join(FLAGS.model_dir, save_name))
```

I'd like to use the saved model to generate summaries from articles. I only found examples on evaluating a model on batches of data but I couldn't find any on using just a single text document to generate summaries.

What I'm trying to accomplish is writing a function that takes a text document as an input and returns the generated summary for it. Something like this:
```python
with tf.Session() as sess:
  saver.restore(sess, "/tmp/model.ckpt")

def generate_summary(text, sess):
    feed_dict = {
        tx.global_mode(): tf.estimator.ModeKeys.PREDICT
    }
    fetches = [
        text, # How should I present text here?
        infer_outputs.predicted_ids[:, :, 0]
    ]

    summary = sess.run(fetches, feed_dict=feed_dict)

    return summary

```

How should I go about this?

Thanks in advance,
Miika

**Comment by ZhitingHu** [comment]
Hi, there are several ways to get text output.

*1) Map text-ids to text in TF*. Use [Vocab.map_ids_to_tokens](https://texar.readthedocs.io/en/latest/code/data.html#texar.data.Vocab.map_ids_to_tokens) to do this, e.g.,
```
text = vocab.map_ids_to_tokens(infer_outputs.predicted_ids[:, :, 0])
```
See an example [here](https://github.com/asyml/texar/blob/master/examples/hierarchical_dialog/hred.py#L137)

You can also:
*2) get text-ids in Python first and map them to text*. You may use [texar.utils.map_ids_to_strs](https://texar.readthedocs.io/en/latest/code/utils.html#id6) for this, e.g.,
```
ids_ = sess.run(infer_outputs.predicted_ids[:, :, 0], feed_dict=feed_dict)
text_ = texar.utils.map_ids_to_strs(ids_, vocab)
```
See an example [here](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/main.py#L127)

**Comment by miikargh** [comment]
That's plenty helpful. Thanks!

**Comment by nutalk** [comment]
did you use the saved model to generate text form a single document?
