### ISSUE TITLE
ValueError: Assignment map with scope only name bert/position_embeddings should map to scope only bert/embeddings/position_embeddings. Should be 'scope/': 'other_scope/'.

### ISSUE THREAD

**Issue by Vibha111094** [asyml/texar#127]
when i try to  do 
model_utils.init_bert_checkpoint(init_checkpoint)
I get 
ValueError:Assignment map with scope only name bert/position_embeddings should map to scope only bert/embeddings/position_embeddings. Should be 'scope/': 'other_scope/'.

This was working fine earlier ,could this be due to the new changes introduced in texar ,as I have not changed my code .

**Comment by ZhitingHu** [comment]
Hi, we've just updated the `TransformerEncoder/Decoder` modules.

Please either use the previous Texar version ([v0.2.0](https://github.com/asyml/texar/releases/tag/v0.2.0)) to use your BERT code, or use the (slightly) updated [bert example](https://github.com/asyml/texar/tree/master/examples/bert) with the lastest Texar.

**Comment by Vibha111094** [comment]
For now I would want to use the previous version as I am in the middle of something very urgent .
Could you please explain how I could get  the previous version .
Because I use colab and session gets reset (every 12 hours ) so I do not have the older version of texar .

**Comment by ZhitingHu** [comment]
Here is the older  version (v0.2)：https://github.com/asyml/texar/releases/tag/v0.2.0

**Comment by Vibha111094** [comment]
Is v0.2.0 the latest one or v0.1.0?
Should I not need v0.1.0?

**Comment by Vibha111094** [comment]
I  used the https://github.com/asyml/texar/releases/tag/v0.1.0

However I am still facing the following issue :
_build() got an unexpected keyword argument 'length_penalty'
looks like length_penalty has been removed from even the older version??
I was in the middle of training , and if I remove length_penalty  there is a incompatability of checkpoints.

**Comment by ZhitingHu** [comment]
Pls use v0.2.0, which is an older version than the one in the master branch now.

**Comment by Vibha111094** [comment]
Thankyou ! It works now:)

**Comment by dearchill** [comment]
Hi! I uses the previous Texar version (v0.2.0) but it still appears to have this problem. Could any other solutions provided? Thank you!

**Comment by ZhitingHu** [comment]
Can you post the error msg?
