### ISSUE TITLE
Loading the Freezed and optimised Graph throws error when laoding back

### ISSUE THREAD

**Issue by santhoshkolloju** [asyml/texar#129]
Hi,

I am using Transformer code for one solving one my problem. I was trying to convert the trained model to tensor-flow lite i followed the following steps.
**Step1 :Freezing The Graph**

python -m tensorflow.python.tools.freeze_graph --input_graph graph.pb --input_checkpoint test_model . --output_graph graph_frozen.pb --output_node_names=transformer_decoder_2/beam_search_op

#this is the last line in bear_search_decode function of TransformerDecoder
outputs = tf.transpose(outputs, [0, 2, 1],name="beam_search_op")

**Step2:Optimise the Graph for Inference**
python -m tensorflow.python.tools.optimize_for_inference --input graph_frozen.pb --output graph_optimized.pb --input_names=Placeholder Placeholder_1  --output_names=transformer_decoder_2/beam_search_op  --placeholder_type_enum=9 9

**Step3: Loading the Graph Back**
with tf.gfile.GFile('graph_optimized.pb', 'rb') as f:
   graph_def_optimized = tf.GraphDef()
   graph_def_optimized.ParseFromString(f.read())

G = tf.Graph()

with tf.Session(graph=G) as sess:
    y, = tf.import_graph_def(graph_def_optimized, return_elements=['transformer_decoder_2/beam_search_op:0'])
    print('Operations in Optimized Graph:')
    print([op.name for op in G.get_operations()])
   
 **This throws following error:**
InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node import/transformer_decoder_2/while/mul_2/y}} = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 3>](import/transformer_decoder_2/while/Switch:1)

Can you please help me with solving this problem

**Comment by ZhitingHu** [comment]
not an expert on tensor-flow lite.

**Comment by ZhitingHu** [comment]
not an expert on tensor-flow lite. 

you may try the "train_greedy" strategy which does not involve a while-loop and see if it works

**Comment by santhoshkolloju** [comment]
I found a way to do that. I have used tensorflow graph transform library to do freezing of graph and  8 bit quantization. Model size got reduced significantly. But still facing problem with inference time.
My model takes around 150 sec with beam size of 3 and max decoding length of 400.both encoder and decoder has 8 layers and 12 blocks. 
Without beam search it comes up in 30 sec. 
Any idea on how can I improve inference time.

**Comment by santhoshkolloju** [comment]
I am running on cpu with 32 cores and 256 gb ram

**Comment by santhoshkolloju** [comment]
I haved used graph transform library from tensorflow to do it

**Comment by nikoliazekter** [comment]
@santhoshkolloju  can you please share more details? Have you managed to successfully convert your model to Tensorflow Lite and run it on device?
