### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by freefuiiismyname** [asyml/texar#132]
When i use transformer decoder to inference, i meet some troubles:1.infer_greedy mode returns two str('sample_id' and 'log_prob'). 2.beam search may get a seq that length much longer than max_decoding_length. 
I'm so upset :((((, and i check my code, it follows your 'transformer_decoder_test.py'. So,some bugs exist in this repository？

**Comment by ZhitingHu** [comment]
Have you run `transformer_decoder_test.py` and passed? Does (`test_decode_infer_greedy`)[https://github.com/asyml/texar/blob/master/texar/modules/decoders/transformer_decoders_test.py#L104] work as you expected?

**Comment by freefuiiismyname** [comment]
I uninstall this ,and use other repository now...

**Comment by wwt17** [comment]
I guess that probably you installed an older version of Texar, while the document you read was updated to the latest version. You may reinstall the latest Texar if you'd like to try again.
