### ISSUE TITLE
vae_text LM text generation <EOS> error

### ISSUE THREAD

**Issue by bjayakumar** [asyml/texar#134]
I am getting following error.

```    _sys.exit(main(argv))
  File "vae_train.py", line 321, in _main
    generate(sess, saver, FLAGS.out)
  File "vae_train.py", line 312, in generate
    end_id = sent.index(vocab.eos_token)
ValueError: '<EOS>' is not in list
```

I am running this model:

https://github.com/asyml/texar/tree/master/examples/vae_text

I am trying to generate after I trained the model.

`python vae_train.py --config config_file --mode predict --model /path/to/model.ckpt --out /path/to/output
`

**Comment by jxhe** [comment]
This is a bug when pretrained VAE fails to generate EOS token, I am fixing it.

**Comment by bjayakumar** [comment]
Thanks. I hope I do not need to retrain the model again.

**Comment by jueliangguke** [comment]
I meet the same problem. It has not been fixed yet?

**Comment by ZhitingHu** [comment]
Fixed
