### ISSUE TITLE
gpt-2 345M model doesn't work

### ISSUE THREAD

**Issue by rjadr** [asyml/texar#162]
The file `gpt2_generate_main.py` still has a reference to the 117M model hardcoded. On line 97-98 it reads
`    proc = processor.get_encoder(
        "gpt2_pretrained_models/model_117M")`
As a result the 345M model fails to load. This is something which is easily overlooked when one has both models installed. I hacked my way around it by changing the reference to the 345M model, but you might want to implement a solution that reads the model from the config_model input variable.

**Comment by ZhitingHu** [comment]
@TomNong can you fix?

**Comment by TomNong** [comment]
Yes, this will soon to be fixed, thanks!
