### ISSUE TITLE
What are the tensorflow versions supported by texar?

### ISSUE THREAD

**Issue by wz111** [asyml/texar#164]
From the previous issue I know 1.13 is supported, but when I run examples/hierarchical_dialog/hred.py on tensorflow1.4.1, I got the following error:

AttributeError: 'Dense' object has no attribute 'compute_output_shape'

For some reason I can't consult the tensorflow api documentation, so I made this issue. Thanks for your attention!

**Comment by ZhitingHu** [comment]
Texar needs at least tf>=1.7  (`compute_output_shape` is supported only by tf>=1.7)

Some of the modules would need higher TF version

**Comment by wz111** [comment]
Thanks for your reply!
