### ISSUE TITLE
vae_text results

### ISSUE THREAD

**Issue by jueliangguke** [asyml/texar#169]
I have run the VAE language model on PTB and Yahoo with the default hyperparameters you give. But the results I obtain are much worse than given in [readme.md](https://github.com/asyml/texar/tree/master/examples/vae_text#language-modeling) when using Transformer as decoder (e.g., 108.31 test PPL and 374.18 test NLL on Yahoo).  I wonder whether the given results are obtained with the default hyperparameters.

**Comment by ZhitingHu** [comment]
I'm upgrading the vae example. Before that, texar [v0.2.0](https://github.com/asyml/texar/releases/tag/v0.2.0) should be able to recover the reported results.

**Comment by ZhitingHu** [comment]
Now the vae_text example can reproduce the reported results with the latest Texar
