### ISSUE TITLE
Run hred.py with an error

### ISSUE THREAD

**Issue by katherinelyx** [asyml/texar#171]
Hello, when I run hred.py and an error occurs:
"UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 4027: surrogates not allowed"
My computer system is Win10.
Could you provide some solutions? Thank you.

**Comment by katherinelyx** [comment]
The problem has been solved. An error is found in 'config_data.py': 
"vocab_file": os.path.join(data_root, 'vocab.txt'),
                "embedding_init": {
                    "file": os.path.join(data_root, 'embedding.txt'),
                    "dim": 200,
                    "read_fn": "load_glove"
               
'os.path.join(data_root, 'embedding.txt') ' should be 'os.path.join(data_root, 'switchboard/embedding.txt')'

**Comment by ZhitingHu** [comment]
I believe the path `os.path.join(data_root, 'embedding.txt')` for embedding initialization is indeed correct. `'embedding.txt'` is under `data/` instead of `data/switchboard`

**Comment by katherinelyx** [comment]
When I download data with your code，embedding.txt and vocab.txt are in data/swithboard. Whatever，problem has been solved. Thank you. ^_^

发自我的 iPhone
