### ISSUE TITLE
Run hierarchical_dialog example with new dataset

### ISSUE THREAD

**Issue by katherinelyx** [asyml/texar#172]
I want to run the hierarchical_dialog example with a new dataset.
The new data has been pre-processed into the same form with 'switchboard', which is demonstrated in the example.
But the 'hred.py' can not run and an error 'An error ocurred while starting the kernel' occurs.
I think something is wrong in the following code:
**step, loss, _ = sess.run(
                    [global_step, mle_loss, train_op], feed_dict=feed)**
Maybe something is not adapted to new dataset in the data pre-processing.
Could you give some advice? Thank you.

**Comment by ZhitingHu** [comment]
Can you post the whole error msg?

**Comment by katherinelyx** [comment]
**The whole error message is as follows:**
An error ocurred while starting the kernel
2019󈚪󈚼 08:39:23.539592: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019󈚪󈚼 08:39:24.576599: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019󈚪󈚼 08:39:24.594739: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2019󈚪󈚼 08:39:25.899310: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019󈚪󈚼 08:39:25.904782: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958] 0 
2019󈚪󈚼 08:39:25.908410: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0: N
2019󈚪󈚼 08:39:25.912216: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4736 MB memory) ‑> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by ZhitingHu** [comment]
It'd be helpful to post the whole error msg before/after `"An error ocurred while starting the kernel"`.

Also, have you tried run on CPU and see if the problem still occurs?
