### ISSUE TITLE
Include rouge in requirements.txt

### ISSUE THREAD

**Issue by claudiohfg** [asyml/texar#173]
`Traceback (most recent call last):
  File "baseline_seq2seq_attn_main.py", line 29, in <module>
    from rouge import Rouge
ModuleNotFoundError: No module named 'rouge'`

Please include "rouge" in requirements.txt

**Comment by ZhitingHu** [comment]
It's indeed in the requirements.txt https://github.com/asyml/texar/blob/master/examples/seq2seq_exposure_bias/requirements.txt
