### ISSUE TITLE
Need some guidance on Narrative Generation

### ISSUE THREAD

**Issue by bchevallereau** [asyml/texar#177]
Hi
I'm working for a company that is looking to generate narratives based on some data. In terms of narrative, we are looking for Adverse Event reports to include in CSR (Clinical Study Reports). Texar seems to be a very good framework to start on that, but I don't have a lot of experience in this area. I looked at your example page, but struggle to see the best project to start with. 
Would you have any additional guidance on where to start? Piece of code that you could re-use?
Thanks

**Comment by ZhitingHu** [comment]
It'd be helpful to know what the inputs and outputs are in your problem, so that we'd pick an example to start with

**Comment by bchevallereau** [comment]
I'm sorry if it has been very long. I'm really struggling to get data from my company to be able to experiment... If I receive them, I'll reopen the ticket. Thanks @ZhitingHu for your patience!
