### ISSUE TITLE
Could you some detail about data in the 'hierarchical dialog generation'

### ISSUE THREAD

**Issue by katherinelyx** [asyml/texar#178]
Hello, I want to run your code on a new dataset, but errors often occur. The only change in the program is dataset, so could you provide some detail or some samples about input data in the 'hierarchical dialog generation'? Thank you.

**Comment by ZhitingHu** [comment]
Example data (`switchboard`) can be downloaded following the README [here](https://github.com/asyml/texar/tree/master/examples/hierarchical_dialog#dataset). Can you run the example with the provided data?

**Comment by katherinelyx** [comment]
Yes, I have successfully run the example with the 'switchboard' data. But when I change to my own data, it failed. Additionally, I already preprocess my data as the same form with 'switchboard'.

**Comment by ZhitingHu** [comment]
The code should work if the data is in the same format as `switchboard`. What error did you get? (it'd be helpful to know the entire error msg)
