### ISSUE TITLE
Using texar for paraphrase generation 

### ISSUE THREAD

**Issue by thefirebanks** [asyml/texar#180]
Hello! 

I am working on a task involving paraphrase generation and was wondering if texar could be used for these purposes - I can think of text summarization as the closest example in the list that you have provided, but I'd love to hear your input regarding what's the best way to approach this. For instance, I would love to generate some question paraphrases using the Quora question-pairs dataset.

Apart from that, thank you for uploading this code, looks great!

**Comment by ZhitingHu** [comment]
I guess a common way to generate paraphrases is through machine translation, e.g., translating a question *x* in English to French *y* and then translating back to get *x'*.
