### ISSUE TITLE
gpt2 text interactive text generation - possible to read from input text?

### ISSUE THREAD

**Issue by GenTxt** [asyml/texar#184]
Hi: 

Thanks for the repo. Everything working great and can even generate text from fine-tuned gpt2 models created with nshepperd's version

Just wondering if it's possible to read lines from an input text in interactive mode instead of typing or copy & pasting text at the prompt? 

Format of input.txt could be a line of text followed by a blank line followed by another line followed by a blank etc.

Each line (prompt)  would be followed by the # of samples in the terminal command.

For example:

This is the first line to be used for text generation in texar's gpt2.

This is the second line ...

And the third .... etc

Thanks

**Comment by ZhitingHu** [comment]
Thanks for the request. This looks like a specialized request, and could be straightforward to implement by oneself. We would probably not include this feature

**Comment by hunterhector** [comment]
In fact, the NLP pipeline being developed is a natural solution to this issue. The pipeline has a nice reader interface that can support this. So we don't need to implement it in Texar.
