### ISSUE TITLE
Bert encoder +transformer decoder?

### ISSUE THREAD

**Issue by ECNUHP** [asyml/texar#190]
is there probability to build a model of the bert as encoder and the transformer as the  decoder?

**Comment by ZhitingHu** [comment]
Yes, it's pretty easy:
```python
encoder = BertEncoder()
output_enc, _ = encoder(inputs=source_text_ids)

decoder = TransformerDecoder(vocab_size=1000)
outputs = decoder(decoding_strategy='train_greedy',   # teacher-forcing decoding (for training)
                  inputs=embedding_fn(target_text_ids))
```
where `embedding_fn` can include both word embedding and position embedding, see [here](https://github.com/asyml/texar/blob/master/examples/transformer/transformer_main.py#L113-L119) for example

**Comment by ECNUHP** [comment]
> Yes, it's pretty easy:
> 
> ```python
> encoder = BertEncoder()
> output_enc, _ = encoder(inputs=source_text_ids)
> 
> decoder = TransformerDecoder(vocab_size=1000)
> outputs = decoder(decoding_strategy='train_greedy',   # teacher-forcing decoding (for training)
>                   inputs=embedding_fn(target_text_ids))
> ```
> 
> where `embedding_fn` can include both word embedding and position embedding, see [here](https://github.com/asyml/texar/blob/master/examples/transformer/transformer_main.py#L113-L119) for example

I am very appreciate for your reply.
Is there a detailed example for use bert as encoder.

**Comment by ZhitingHu** [comment]
The [seq2seq](https://github.com/asyml/texar/blob/master/examples/seq2seq_attn/seq2seq_attn.py) example can be a good reference--just replace `BidirectionalRNNEncoder` with `BertEncoder`. Pls feel free to let us know if you have any questions in adapting the example

**Comment by ZhitingHu** [comment]
closed due to inactivity

**Comment by ZhitingHu** [comment]
closed due to inactivity
