### ISSUE TITLE
import texar.tf as tx .No module named 'texar.tf' via pip install

### ISSUE THREAD

**Issue by pol690** [asyml/texar#198]
Hi guys 

I am very new to texar. I have installed it via pip.  When trying to run one of the examples, namely `seq2seq_exposure_bias`. I get the following: `File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'texar.tf'` . I have tried to run it via jupyter and bash, and neither works, nor a direct bash command `python import texar.tf as tx`.

Then I have tried to run the example from the git cloned texar repo. The texar.tf is imported successfully in that case, but then I get `tensorflow.python.framework.errors_impl.NotFoundError: ./data/iwslt14/vocab.de; No such file or directory` when running `python interpolation_main.py \
    --config_model configs.config_model \
    --config_data configs.config_iwslt14 \
    --lambdas_init [0.04,0.96,0.0] \
    --delta_lambda_self 0.06 \
    --delta_lambda_reward 0.06 \
    --lambda_reward_steps 4`

Tensorflow is installed and working.

**Comment by mongolia19** [comment]
The same issue here

**Comment by ZhitingHu** [comment]
For now, `import texar.tf` is only supported in `v0.2.3-unreleased` (installed from the source). For `v0.2.2` (installed from PyPI), please use `import texar`. We will update to avoid the confusion asap.

**Comment by TomNong** [comment]
Hi @pol690, it seems you tried to run example `seq2seq_exposure_bias` and it occurs error, did you download the data before running `python interpolation_main.py \ --config_model configs.config_model \ --config_data configs.config_iwslt14 \ --lambdas_init [0.04,0.96,0.0] \ --delta_lambda_self 0.06 \ --delta_lambda_reward 0.06 \ --lambda_reward_steps 4`?

**Comment by TomNong** [comment]
If not, you can download `iwslt14` dataset by using `python utils/prepare_data.py --data iwslt14` and run that example again.

**Comment by pol690** [comment]
Thanks @TomNong for getting back! The thing is that I am particularly interested in text summarization, that's why I went only for the giga dataset, and even after successfully downloading it (and  iwslt14) it raises the mentioned error.

On the other hand, when I go `iwslt14` sadly something else happens. The script goes to the first epoch/steps and never reaches the second one regardless of how long I wait.

`2019-08-15 13:47:00.483731: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-15 13:47:00.508150: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2019-08-15 13:47:00.508512: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x529b9e0 executing computations on platform Host. Devices:
2019-08-15 13:47:00.508536: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-15 13:47:01.693605: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
step=0, loss=190.0478
`

**Comment by TomNong** [comment]
@pol690  thanks for the information. For the prior error, since it raises after downloading the data, I would suggest you to check the directory by  `ls ./data/iwslt14/vocab.de` in same directory to see if it really exists.

For the non-response issue, I think it is because the training scripts are supposed to create a `training_log_xxx` directory and put the step printings inside as `training_logX.txt`, you should be able to see it in the same directory.

**Comment by ZhitingHu** [comment]
closed due to inactivity
