### ISSUE TITLE
sequence to sequence code with GPT2/GPT/BERT

### ISSUE THREAD

**Issue by juliahane** [asyml/texar#232]
Hi
I am looking for a sequence to sequence generation code with gpt2/gpt or BERT, I was wondering if you have a code available in this repo, and I greatly appreciate to tell me how I can run a sequence to sequence model with the mentioned models. thanks

**Comment by gpengzhi** [comment]
Hello. Thanks for your interest in `Texar`. You can take a look at this example:
https://github.com/asyml/texar/tree/master/examples/gpt-2
