### ISSUE TITLE
Possible bug in seq2seq_attn

### ISSUE THREAD

**Issue by shiva-z** [asyml/texar#242]
I tried to train seq2seq_attn on iwslt14 with this command: `python seq2seq_attn.py --config_model config_model --config_data config_iwslt14` and I got these results for epoch 15:
```
step=0, loss=12.3963
step=500, loss=17.8061
step=1000, loss=17.9841
step=1500, loss=17.3628
step=2000, loss=23.1591
step=2500, loss=14.6512
step=3000, loss=20.4959
step=3500, loss=22.3177
step=4000, loss=21.8172
step=4500, loss=18.0917
val epoch=14, BLEU=0.0000; best-ever=0.0000
test epoch=14, BLEU=0.0000
```

**Comment by gpengzhi** [comment]
Thanks for your interest in `texar`! I will try to reproduce your result and check if it is a bug.

**Comment by ZhitingHu** [comment]
The bug in beam_search_decode is fixed.  The seq2seq_attn example now reproduces the claimed results
