### ISSUE TITLE
How to add an auxilary loss to gpt2 causal LM loss?

### ISSUE THREAD

**Issue by Hannabrahman** [asyml/texar#244]
Hi,

I want to have an auxiliary loss (L2) being added to gpt2 causal LM loss (L1) and fine-tune it with respect to both loss (L1+L2).

Would you please guide me if it is possible to do it within taxer and how?

Thanks

**Comment by ZhitingHu** [comment]
This looks like a very basic need. Just add up the two losses and create a train op, like in naive TF. Here is an example: [creating train op](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L142) and [adding up loss](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L134)

**Comment by Hannabrahman** [comment]
> This looks like a very basic need. Just add up the two losses and create a train op, like in naive TF. Here is an example: [creating train op](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L142) and [adding up loss](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L134)

yeah yeah I was able to that.
Just I could not have ```max_decoding_length``` be different than ```max_sequence_length``` which I define for preparing the tfrecord files.
I am pretty sure that we can have a different max_decoding_length than max_seq_length, right?

**Comment by ZhitingHu** [comment]
Yes you can
