### ISSUE TITLE
TF compatibility

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar#254]
These parts in `dynamic_decode` are not compatible with TF < 1.14: 

- `TensorShape.rank`: https://github.com/asyml/texar/blob/master/texar/tf/modules/decoders/dynamic_decode.py#L136
- `tf.get_static_value`: https://github.com/asyml/texar/blob/master/texar/tf/modules/decoders/dynamic_decode.py#L63

Pls replace with alternative APIs for broader compatibility

**Comment by gpengzhi** [comment]
Since `tensorflow-probability >= 0.7` requires `tensorflow >= 1.14`, a better way might be directly updating our `requirements.txt`.

**Comment by gpengzhi** [comment]
Since `tensorflow-probability >=0.7` requires `tensorflow >= 1.14`, it might be better to update `requirements.txt` instead.

**Comment by ZhitingHu** [comment]
where is `tensorflow-probability >=0.7` required? In the README it says`tensorflow_probability >= 0.3.0 (but < 0.8.0)`?

**Comment by gpengzhi** [comment]
`distributions` in `tensorflow_probability` is used in many modules. `tensorflow_probability 0.8.0` requires `tensorflow > 1.14.0`, but we did not support `tensorflow 1.15.0` at that time.

**Comment by gpengzhi** [comment]
resolved in #260
