### ISSUE TITLE
Sentence interpolation

### ISSUE THREAD

**Issue by Bachstelze** [asyml/texar#30]
How can I run the pristine sentence interpolation with the Variational Autoencoder?

**Comment by jxhe** [comment]
The current vae_text example only covers the usage for VAE training, I am adding sentence generation feature to the vae_text example now. You can also refer to #24 for how to generate sentences.

**Comment by ZhitingHu** [comment]
@jxhe any updates on this?

**Comment by jxhe** [comment]
Sorry I was quite busy in the past days. I will finish this by Friday.

**Comment by Bachstelze** [comment]
Thanks for the hint. But don't overhasty. We should have time to build a clear architecture of the VAE
https://github.com/asyml/texar/tree/master/examples/vae_text
If get the papers right then there are different abilities from Imputing missing words, word dropout for interpolation, sampling from the posterior and conditional text generation. Getting them all in one architecture is quit ambitious, because they all need different parameters for the decoder. The word dropout even needs for each interpolation step a different training.
So my first focus isn't one functionality rather settle the architecture than.
Or what do you think? Let me know your plans and ideas.

**Comment by ZhitingHu** [comment]
Thanks @Bachstelze for summarizing the different use cases. word-dropout has been supported in [WordEmbedder](https://github.com/asyml/texar/blob/master/texar/modules/embedders/embedders.py#L162).

Perhaps it's not necessary to support everything in one code. We can have one code for simple language modeling and (unconditional) generation, and another for, e.g., interpolation. The current [vae_text](https://github.com/asyml/texar/tree/master/examples/vae_text) example supports only language modeling, and we shall add the (unconditional) generation functionality (i.e., sampling from the prior and generate a sentence accordingly).
