### ISSUE TITLE
vae_train.py

### ISSUE THREAD

**Issue by Kid31817081** [asyml/texar#31]
Excuse me. I want to ask you some questions.Could you help me solve them?
     Firstly,When I run the vae_train.py,I encounter a problem like that"`ImportError: No module named 'config'`",
     so i copy the file named config.py ,which under the text_style_transfer, into the vae_text .
After that, i run the program again. But there comes another problem like that 
" `  File "G:/NLP/texar-master/texar-master/examples/vae_text/vae_train.py", line 64, in _main
    train_data = tx.data.MonoTextData(config.train_data_hparams)
AttributeError: module 'config' has no attribute 'train_data_hparams'"`

   what should I do next？ thank you.

**Comment by ZhitingHu** [comment]
You should use the config files provided in `examples/vae_text/`. For example, when running with 
```
python vae_train.py --config config_trans_ptb
```
the config file `config_trans_ptb.py` is used.
