### ISSUE TITLE
A Question About the Example -- sentence_classifier

### ISSUE THREAD

**Issue by mahaoxiang822** [asyml/texar#32]
I am a new user of texar, when I try one of the examples named "sentence_classifier"(https://github.com/asyml/texar/tree/master/examples/sentence_classifier), I find some problems hard to resolve.
In the example, the language of the data is english however I want to try it in chinese. I just replace the SSTdata with my data. 
Here is the form of the data  I use:
`2 但是您的所作所为不合适。`
`1 我觉得这个苹果味道一般。`
`0 今天终于修正了一个错误。` 
About the vocab ,I use my own word segmenter for chinese sentence.
The program displays an error:
![image](https://user-images.githubusercontent.com/36100173/46259625-633dab00-c50e-11e8-9834-c9241ef62cbb.png)
I guess it is because the size of the batch. So I change the batch size from 50 to 64 in config_kim.py. 
Then there is another error appears:
![image](https://user-images.githubusercontent.com/36100173/46259650-b31c7200-c50e-11e8-8334-ce81fdc948f3.png)
I don't know how to explain it so I hope someone can tell me if I use Texar incorrectly or there are other problems exist.

**Comment by ZhitingHu** [comment]
The error is because the (1) input sentence length < filter size, and (2) the default config does not use padding. 

For (1), it looks your data is not tokenized. Texar does not tokenize the text. The input sentence should be like "但是 您 的 所作所为 不 合适", i.e., tokens are separated by whitespaces.

The code should work after fixing (1). To add padding, set the hyperparameter `"other_conv_kwargs": {"padding": 'SAME'},` in the dict `clas` in the config file `config_kim.py`

**Comment by mahaoxiang822** [comment]
Thank you very much ,it really works.
I want to let the program to classify my test sentence so I need to get the result of the class. I change the fetches to `fetches = {
            "accu": accu,
            "pred": pred,
            "batch_size": tx.utils.get_batch_size(batch['y'])
        }`.
I think the key:pred will be the list of the result however the order of the list is messy rather than in the order of the test data. Is there some solution for this problem?

**Comment by ZhitingHu** [comment]
Not quite sure what you meant by "the order of the list is messy". `pred` should be a Tensor of shape `[batch_size]`.

**Comment by mahaoxiang822** [comment]
For example, the label of the test data is [0,1,0,1] and when I print the pred ,it is [1,0,0,1] although the acuuracy is 100%. Maybe it is because the shape of the data is smaller than the size of batch?

**Comment by ZhitingHu** [comment]
`accu` is computed using `pred` and the ground-truth labels [here](https://github.com/asyml/texar/blob/master/examples/sentence_classifier/clas_main.py#L57).  `accu`=100% means `pred` matches ground truth. Can you print out the ground truth to see if it's correct?

To avoid batch smaller than `batch_size`, you may set `allow_smaller_final_batch` to False in the data hyperparameters ([doc](https://texar.readthedocs.io/en/latest/code/data.html#database))

**Comment by mahaoxiang822** [comment]
I have solved my problem . Thank you very much!
