### ISSUE TITLE
example about text summarization

### ISSUE THREAD

**Issue by tangtangsiqi** [asyml/texar#33]
I am wondering if there are examples about text summarization

**Comment by ZhitingHu** [comment]
We will add a sentence summarization example soon, which is essentially still a sequence to sequence model as [here](https://github.com/asyml/texar/tree/master/examples/seq2seq_attn).

For more structured models for long text summarization, it'd be great if someone could contribute:)

**Comment by ZhitingHu** [comment]
The seq2seq model for sentence summarization is now available [here](https://github.com/asyml/texar/tree/master/examples/seq2seq_exposure_bias).
