### ISSUE TITLE
transformer_main.py

### ISSUE THREAD

**Issue by TomNong** [asyml/texar#34]
Excuse me, I followed the example of transformer with the IWSLT'15 EN-VI data, after I ran `python transformer_main.py --run_mode=train_and_evaluate --config_model=config_model --config_data=config_iwslt15 `, I got error:

 `Traceback (most recent call last):
  File "transformer_main.py", line 271, in <module>
    main()
  File "transformer_main.py", line 89, in main
    encoder = TransformerEncoder(hparams=config_model.encoder)
  File "/home/nongshibiao/Documents/texar/texar/modules/encoders/transformer_encoders.py", line 128, in __init__
    layers.get_initializer(self._hparams.initializer))
  File "/home/nongshibiao/Documents/texar/texar/core/layers.py", line 413, in get_initializer
    modules)
  File "/home/nongshibiao/Documents/texar/texar/utils/utils.py", line 197, in check_or_get_instance
    ret = get_instance(ret, kwargs, module_paths)
  File "/home/nongshibiao/Documents/texar/texar/utils/utils.py", line 239, in get_instance
    (class_.__module__, class_.__name__, key, list(class_args)))
ValueError: Invalid argument for class tensorflow.python.ops.init_ops.VarianceScaling: distribution, valid args: []`

I go back to the code and it seems the valid args could be not empty. Is it because I missed loading the instance at some point? Thank you.

**Comment by ZhitingHu** [comment]
This is probably because the TF version you use is not compatible. Which version are you using?

@haoransh could you track this issue?

**Comment by TomNong** [comment]
You are right, I'm using cpu version tensorflow, and it works when I degrade tensorflow1.11.0 to tensorflow1.7.0, while I got the warning 
`2018-10-08 02:57:48.051285: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`
it should be OK if I rebuild my tensorflow from source

**Comment by ZhitingHu** [comment]
I think tf-v1.10 would work as well.

**Comment by ZhitingHu** [comment]
Now tf-v1.11 should also work. 

fixed by commit ac57498ffeb10d59de68930a7970e7e8100f2e28
