### ISSUE TITLE
How can I generate text from discrete set of keywords?

### ISSUE THREAD

**Issue by sharavsambuu** [asyml/texar#37]
How can I generate text from discrete set of keywords?
Are there any examples in the Texar? or any clue to accomplish to this task?

**Comment by ZhitingHu** [comment]
Not sure exactly what you meant by generating text from keywords. One simple solution is just to use a seq2seq model that encodes the keywords (so the keywords are kind of soft constraint, not necessarily occur in the generated text). 
 
Another solution would be to use some constrained decoding that ensures keywords will occur in the generated text. Texar has not implemented such decoding strategy yet. Contributions are welcome
