### ISSUE TITLE
Label for text_style_transfer

### ISSUE THREAD

**Issue by rainyrainyguo** [asyml/texar#42]
I can not read in non-integer label like 0.456 for text_style_transfer code:
iterator = tx.data.FeedableDataIterator({'train_g': train_data,'val': val_data, 'test': test_data})

**Comment by ZhitingHu** [comment]
To read in non-integer label, set the `data_type` [here](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/config.py#L35) to `'float'`.

Note that the example assumes binary label, e.g., the code [here](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L60) flips the label by `1-label`
