### ISSUE TITLE
shape mismatch bug in hred and cannot reproduce the result

### ISSUE THREAD

**Issue by haofuml** [asyml/texar#47]
Hi, 

I am trying to reproduce the result of hred. But I encountered the following error
"ValueError: sequence_length must be a vector of length batch_size, but saw shape
: (?, ?)"

I think the bug lies in hred.py line 81, the related code block from line 78 - 82 is :
`ecdr_states = encoder(
        context_embed,
        medium=['flatten', _add_source_speaker_token],
        sequence_length_minor=data_batch['source_length'],
        sequence_length_major=data_batch['source_utterance_cnt'])`

I fixed it by reshaping the data_batch['source_length'] to a vector and the program can run. However the result is far worse than either the paper or the reported chart. Here is my result:

-- bleu-1 prec=0.2850111431585633, recall=0.28461374427599595
 -- bleu-2 prec=0.1638788596563101, recall=0.16767654177822935
 -- bleu-3 prec=0.10135466013603585, recall=0.10516786599271233
 -- bleu-4 prec=0.050318838607421, recall=0.05182164173830952

Also is the n-gram bleu score here individual or cummulative(i.e. the average of 1-gram,...n-gram)? Thanks.

**Comment by ZhitingHu** [comment]
Fixed all issues. Thank you for reporting this.

n-gram bleu scores should be cumulative.
