### ISSUE TITLE
text_style_transfer multy GPU

### ISSUE THREAD

**Issue by baobaozhou** [asyml/texar#49]
When I want to use more than 1 gpu running program, no matter how I add it, I cannot work at the same time with multiple gpus. I don't know why, but where can I modify it to ensure that multiple gpus can be used at the same time

**Comment by ZhitingHu** [comment]
At this point you can just use TF built-in functions for multi-gpu. For example, you may use `tf.estimator` for data-parallelism, or `tf.device` for model-parallelism. 

We are adding ease-of-use multi-gpu APIs to Texar, which would be ready soon.

**Comment by ZhitingHu** [comment]
We've added support for distributed model training with multiple GPUs. Please see the examples of [distributed_gpu](https://github.com/asyml/texar/tree/master/examples/distributed_gpu) and [bert](https://github.com/asyml/texar/tree/master/examples/bert).
