### ISSUE TITLE
AttributeError: 'Dense' object has no attribute 'compute_output_shape'

### ISSUE THREAD

**Issue by rajiv-kp** [asyml/texar#52]
running into this error on both seq2seq_attn and seq2seq_exposure_bias
ran the code for training as specified:

`python seq2seq_attn.py --config_model config_model --config_data config_toy_copy`

@ZhitingHu

**Comment by ZhitingHu** [comment]
what TF version are you using? With tf-v1.11, `tf.layers.Dense` does have the `compute_output_shape` method

**Comment by rajiv-kp** [comment]
this is a TF version issue. rectified, thanks!
