### ISSUE TITLE
no seq2seq_gan example

### ISSUE THREAD

**Issue by rickykaka** [asyml/texar#61]
There is no example code for gan training with seq2seq, I know it is somewhat like a combination of seq2seq_attn and seqgan, but still not sure about how to do it specifically. Can someone show me some code to do it properly?
Thanks!!

**Comment by ZhitingHu** [comment]
Building seq2seq with gan training is pretty straightforward. 
Starting from `seqgan`, you basically want to replace the language model architecture in `seqgan` with the seq2seq architecture in `seq2seq_attn`. That is, replace Line.58-78 of `seqgan` with Line.48-60 of `seq2seq_attn`
