### ISSUE TITLE
BERT gives output of last layer

### ISSUE THREAD

**Issue by santhoshkolloju** [asyml/texar#74]
How to get the output from last 4 layers of bert

**Comment by haoransh** [comment]
Currently transformer_encoder only returns the output of last layer. If you want get the output from multiple layers, you need to collect [the output]( https://github.com/asyml/texar/blob/master/texar/modules/encoders/transformer_encoders.py#L401) from [the layers you want to inspect ](https://github.com/asyml/texar/blob/master/texar/modules/encoders/transformer_encoders.py#L352)
