### ISSUE TITLE
Distributed Training On horovod

### ISSUE THREAD

**Issue by santhoshkolloju** [asyml/texar#84]
I Am trying to run the transformer model on multiple GPUS(4),i see that model is replicated 4 times instead of running in parallel .I see each iteration is run 4 times . is this expected?

**Comment by ZhitingHu** [comment]
Yes. Horovod supports data parallelism, which is to replicate model N times and run in parallel by feeding different data. Make sure you have partition the data so that each model replicate will see different data batches in each iteration.

**Comment by haoransh** [comment]
For your reference, you can have a look of our documentation of the data sharding section here https://github.com/asyml/texar/tree/master/examples/distributed_gpu#adapting-single-gpu-code-for-distributed-training and one ad-hoc implementation(https://github.com/asyml/texar/blob/master/examples/distributed_gpu/ptb_reader.py#L43), to have a look how to make sure different processes receive different data batches.

**Comment by santhoshkolloju** [comment]
Thanks for the reference.
I am using Bert code which is distributed as I have my data in tf records format. 
dataset = file_based_input_fn_builder(
            input_file=train_file,
            seq_length=max_seq_length,
            is_training=True,
            drop_remainder=True,
            is_distributed=is_distributed)({'batch_size': batch_size})
This piece of code will throw error because if we mention batch size as 32 internally file_based_input_fn_builder divided it into batch size of 8 if I have 4 gpus and then you are again specifying batch size after we get the data set also
