### ISSUE TITLE
Transformer Inference is very slow

### ISSUE THREAD

**Issue by santhoshkolloju** [asyml/texar#86]
Inference is very slow ...my max seqlen is 400 and it takes around 500ms to 800ms Is there a way to improve the the inference time?

**Comment by ZhitingHu** [comment]
This should be a standard implementation of transformer inference decoding. I'm not sure about further speedup

You may use multiple GPUs to do inference on a batch in parallel.

**Comment by santhoshkolloju** [comment]
can you guide me how to inference on multiple gpus..?
can we do it on multiple cores on cpu as well..?

**Comment by ZhitingHu** [comment]
Just noticed that `horovod` (the library used in Texar for distributed training) does not directly support distributed inference at deployment time.

The simplest way then is to launch the program on different GPUs (or CPUs) separately, using different data shads.

**Comment by guotong1988** [comment]
Same question, thank you.
