### ISSUE TITLE
Need some help to train gpt-2. Thank you very much!

### ISSUE THREAD

**Issue by guotong1988** [asyml/texar#92]
The figure below is from the README of gpt-2.

![image](https://user-images.githubusercontent.com/4702353/53620647-a7081e00-3c2e-11e9-81d1-0ed96f4ea515.png)

`source_hidden_states` and some other variables are missing, if I coding based on `gpt2_generate_main.py`.

Hope you could please provide a more detailed example? or only an related example link of other model is OK.

Thank you!

**Comment by ZhitingHu** [comment]
Usually, `memory` is set to an encoder's output for the decoder to attend to. For example:

```python
embedder = tx.modulees.WordEmbedder(vocab_size, hparams=config_embedder)
encoder = tx.modules.TransformerEncoder(hparams=config_encoder)
source_hidden_states = encoder(
    inputs=embedder(data_batch['source_text_ids']),
    sequence_length=data_batch['source_length'])
```

You may also refer to Texar's other examples, such as [seq2seq_attn](https://github.com/asyml/texar/blob/master/examples/seq2seq_attn/seq2seq_attn.py#L37) and [transformer](https://github.com/asyml/texar/blob/master/examples/transformer/transformer_main.py#L85-L108). Note that the seq2seq_attn example uses RNN-based encoder/decoder, but their interfaces are basically the same with the Transformer-based encoder/decoder.

**Comment by guotong1988** [comment]
Thank you, I will try it. Or reopen this issue.

**Comment by guotong1988** [comment]
In `gpt2_generate_main.py`, there is only a TransformerDecoder.

But If I add your code above, there will be TransformerEncoder and TransformerDecoder.

So I can not restore the model from the checkpoint.

**Comment by ZhitingHu** [comment]
Can you post the error msg of loading from the checkpoint?

@TomNong I believe the checkpoint loader can still work even if there are extra variables?

**Comment by guotong1988** [comment]
Thank you.
In fact, I don't know the model structure of gpt-2.
I only guess that the checkpoint do not work because the model do not match.

**Comment by ZhitingHu** [comment]
We used a customized checkpoint loader which allows extra variables to be initialized randomly if they are not included in the OpenAI gpt2 checkpoint.

**Comment by TomNong** [comment]
Sorry I just see the issue, we use OpenAI gpt2 checkpoint in the example, basically we initialize those variables matched to the checkpoint variables, not sure if extra variables be initialized in this way.
